"""URLs to scrape"""


COFFEE_PAGES = [
#from Sprudge sponsors:
    "http://49thcoffee.com/collections/coffee",
    "http://barnine.us/collections/all",
    "http://barnine.us/collections/coffee",
    "https://bluebottlecoffee.com/store/coffee",
    "http://store.ceremonycoffee.com/coffees/",
    "https://counterculturecoffee.com/store/coffee:",
    "http://www.dogwoodcoffee.com/collections/coffee",
    "https://store.equatorcoffees.com/coffees/",
    "http://www.fiveelephant.com/collections/shop",
    "http://www.intelligentsiacoffee.com/products/coffee",
    "http://joecoffeeshop.myshopify.com/collections/coffee",
    "http://kaldiscoffee.com/collections/coffee",
    "http://www.lacolombe.com/pages/coffee",
    "https://madcapcoffee.com/buy/coffee/",
    "http://mrespresso.com/coffee/",
    "http://theroasters.com.au/coffee-at-the-northbridge-coffee-roasters/",
    "http://www.olympiacoffee.com/collections/Coffees",
    "http://www.onyxcoffeelab.com/coffee",
    "https://www.philsebastian.com/shop/coffee/",
    "http://populace.coffee/collections/coffee",
    "http://store.ptscoffee.com/coffees/",
    "http://www.reanimatorcoffee.com/store/?category=Coffee",
    "https://squareup.com/market/revelatorcoffee",
    "https://www.sharecoffeeroasters.com/coffees-subscription-choices",
    "http://spyhousecoffee.com/pages/offerings",
    "https://www.stumptowncoffee.com/products",
    "https://www.stumptowncoffee.com/coffee",
    "https://www.tobysestate.com.au/store/coffee.html",
    "http://www.tonyscoffee.com/shop/product-category/coffee/",
    "http://www.vervecoffeeroasters.com/collections/coffee",
    "http://wateravenuecoffee.com/collections/beans",
    #added to expand markov dictionary size: sf, pdx, nordic
    "https://www.sightglasscoffee.com/shop",
    "http://fourbarrelcoffee.com/product-category/coffees/",
    "http://fourbarrelcoffee.com/product-category/delapaz/",
    "http://ritual.myshopify.com/collections/coffee",
    "http://www.heartroasters.com/collections/beans",
    "http://coavacoffee.com/collections/espresso",
    "http://coavacoffee.com/collections/brewed-coffee",
    "https://timwendelboe.no/coffee",
    "http://www.dropcoffee.com/collections/beans",
    #added from web mentions
    "http://www.klatchroasting.com/All_Coffees_s/389.htm",
    "http://shop.parlorcoffee.com/",
    "http://rubycoffeeroasters.com/",
    "https://varietycoffeeroasters.com/?page_id=493",
    #added from Sweet Maria's site
    "https://legacy.sweetmarias.com/library/content/origin-pages",
    "https://www.sweetmarias.com/category/green-coffee/central-north-america",
    "https://www.sweetmarias.com/category/green-coffee/south-america",
    "https://www.sweetmarias.com/category/green-coffee/africa-and-arabia",
    "https://www.sweetmarias.com/category/green-coffee/islands"
]
